stages:
  load_data:
    cmd: python src\load_data.py --config=params.yaml
    deps:
      - src\get_data.py
      - src\load_data.py
      - data_given\winequality-red.csv
    outs:
      - data\raw\winequality.csv

  split_data:
    cmd: python src\split_data.py --config=params.yaml
    deps:
      - src\get_data.py
      - data\raw\winequality.csv
    outs:
      - data\processed\train_data.csv
      - data\processed\val_data.csv
  train_n_eval:
    cmd: python src\model.py --config=params.yaml
    deps:
      - data\processed\train_data.csv
      - data\processed\val_data.csv
      - src\model.py
    params:
      - estimators.ElasticNet.params.alpha
      - estimators.ElasticNet.params.l1_ratio
    metrics:
      - report\score.json:
          cache: False
      - report\params.json:
          cache: False

