base:
  project: MLOps_Wine
  random_state: 42
  target_col: TARGET

data_source:
  local: data_given\winequality-red.csv

load_data:
  raw_data: data\raw\winequality.csv

split_data:
  train_path: data\processed\train_data.csv
  val_path: data\processed\val_data.csv
  val_size: 0.2

estimators:
  ElasticNet:
    params:
      alpha: 0.9
      l1_ratio: 0.4

model_dir: saved_models

reports:
  params: report\params.json
  scores: report\score.json

